### ISSUE TITLE
Proposal: Include "Music Ontology" vocabulary

### ISSUE THREAD

**Issue by musicog** [thisismattmiller/triple-builder#1]
We are planning on running a tutorial day at the end of this month on Music and Linked Data, and the triple builder seems like an excellent tool to get tutorial participants up and running. However, we would need it to be pre-populated with terms from the Music Ontology (http://purl.org/ontology/mo/).

Please could you kindly let me know

- whether you would be willing to incorporate the MO within the Triple Builder
- whether this is realistically doable in the coming few weeks?

I would be happy to generate a JSON object corresponding to the MO for 
https://github.com/thisismattmiller/triple-builder/blob/master/assets/vocabs.json
...if that would be useful. Are there further steps required to incorporate a new vocabulary?

Thanks for your consideration!

**Comment by thisismattmiller** [comment]
Okay I've updated the app and added music ontology. Let me know if you see any problems. 
https://tb.semlab.io

Sorry for not seeing this earlier. -Matt
